### ISSUE TITLE
关于gait数据集预处理的问题

### ISSUE THREAD

**Issue by Antleaf-0921** [BICLab/Attention-SNN#7]
在gait数据集上，代码细节中需要加载train_data.npy和train_target.npy，而原始数据集中只有txt文件，请问这一部分是怎么进行处理划分的呢？

**Comment by Gausx** [comment]
MA_SNN/DVSGait/DVS_gait_data_process/DVS128_Gait_dataloaders.py  具体查看这个文件 里边会有流程将txt 转化为npy数据
