### ISSUE TITLE
关于论文中的dt和T

### ISSUE THREAD

**Issue by Mouseminar** [BICLab/Attention-SNN#8]
<img width="48" alt="T" src="https://github.com/BICLab/Attention-SNN/assets/127723802/4ff11cb9-4bc3-4476-a5d4-959045dc3d47">

您好，DVS128 Gesture的一条数据平均时间是6s，但论文中的 dt*T = 15 * 60 = 900ms，是不是可以认为您只使用了一条数据的前0.9s的信息，这样做不会丢失掉信息吗？

**Comment by BICLab** [comment]
这其实是一种数据增强策略。请参照我们之前工作《Temporal-wise Attention Spiking Neural Networks for Event Streams Classification》中的描述。

**Comment by BICLab** [comment]
我们在另一个工作中提供了更详细的关于事件流处理中，dt和T对任务性能的影响。请参考《Sparser spiking activity can be better: Feature Refine-and-Mask spiking neural network for event-based visual recognition》。

**Comment by Mouseminar** [comment]
> 我们在另一个工作中提供了更详细的关于事件流处理中，dt和T对任务性能的影响。请参考《Sparser spiking activity can be better: Feature Refine-and-Mask spiking neural network for event-based visual recognition》。

好的，感谢😊
